version: '3.8'

services:
  db:
    container_name: internet_blog_db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.prod.env.db
    volumes:
      - pg_data:/var/lib/postgresql/data/

  web:
    container_name: internet_blog_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.prod.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  nginx:
    container_name: internet_blog_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

  redis:
    container_name: internet_blog_redis
    image: redis
    depends_on:
      - web

  celery:
    container_name: internet_blog_celery
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A core worker -l INFO
    env_file:
      - ./.prod.env
    depends_on:
      - redis
      - web

  celery-flower:
    container_name: internet_blog_celery_flower
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    command: celery -A core flower -l INFO
    env_file:
      - ./.prod.env
    depends_on:
      - celery
    
volumes:
  pg_data:
  static_volume:
  media_volume: