version: '3.8'

services:
  web:
    container_name: internet_blog_web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.prod.env
    depends_on:
      - db
    
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  db:
    container_name: internet_blog_db
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
     - ./.prod.env.db
    
  nginx:
    container_name: internet_blog_nginx
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  redis:
    container_name: internet_blo_redis
    image: redis

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A core worker -l INFO
    env_file:
      - ./.prod.env

  celery-flower:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A core flower -l INFO
    env_file:
      - ./.prod.env
    ports:
      - 5555:5555
    
volumes:
  pg_data:
  static_volume:
  media_volume: