# Generated by Django 4.1.5 on 2023-01-24 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_describe_alter_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 14, 46, 55, 181839), verbose_name='Publication date'),
        ),
    ]
