# Generated by Django 4.1.5 on 2023-01-24 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date'),
        ),
    ]
