# Generated by Django 4.1.5 on 2023-02-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_reaction_author_alter_reaction_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='describe',
            field=models.CharField(max_length=90, verbose_name='Describe'),
        ),
    ]
