# Generated by Django 4.1.5 on 2023-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='0.png', upload_to='user_avatar/', verbose_name='avatar'),
        ),
    ]
