version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: .
    command: python /usr/src/server/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/server
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: